tech2metailblog/books/forms.py
#books/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BooksPostForm(FlaskForm): 
    title = StringField('Title',validators=[DataRequired()])
    author = StringField('Author',validators=[DataRequired()])
    published_by = StringField('Publisher',validators=[DataRequired()])
    published_at = StringField('Published_at',validators=[DataRequired()])
    img_link = StringField('img_link',validators=[DataRequired()])
    ecsite_link = StringField('ECsite_link',validators=[DataRequired()])
    text= TextAreaField('Text',validators=[DataRequired()])
    submit=SubmitField('Post')

tech2metailblog/books/views.py
import os, json
from flask import request, redirect, url_for, render_template, flash, session, abort
from flask_login import  login_required, current_user
from tech2metailblog import db
from tech2metailblog.models import Books, BooksPost
from tech2metailblog.books.forms import BooksPostForm
from flask import Blueprint
from tech2metailblog.books.spread_sheet import create_df
import pandas as pd


books = Blueprint('books', __name__)
bookspost = Blueprint('bookspost', __name__)

'''
basedir = os.getcwd()
print(basedir)
l = basedir.split('/')
del l[-1]
l_new = l[0]
for i in range(len(l)):
    l_new = os.path.join(l_new,l[i])
basedir = os.path.join("/",l_new)
dir = os.path.join(basedir,'secrets')
json_file = os.path.join(dir,"admin.json")
open_json = open(json_file,'r')
'''
admin_user = os.getenv('ADMIN_USER_NAME')
# admin_user = 'administrator'
@books.route('/bookshelf')
def create_bookshelf():
    df=create_df()
    rows = df.shape[0]
    for i in range(1,rows+1):
        dict = df[:i:].to_dict()
        try:
            books= Books(
                title = dict['title'][i],
                author = dict['author_family'][i] + " " + dict['author_first'][i],
                published_by = dict['published_by'][i],
                published_at = dict['published_at'][i],
                img_link = dict['img_link'][i],
                pur_link = dict['pur_link'][i]
            )
            db.session.add(books)
            db.session.commit()
            flash('データ作成完了')
        except:
            continue
    return redirect(url_for('books.show_books'))

@books.route('/books/shelf')
def show_shelf():
    books = Books.query.all()
    return render_template('books/shelf.html', books=books)
   
@books.route('/books')
@login_required
def show_books():
    if current_user.username == admin_user:
        books = Books.query.all()
        return render_template('books/index.html', books=books)
    else:
        return render_template('error_pages/403.html')
        
    


@books.route('/books/new', methods=['GET','POST'])
@login_required

def add_books():
    if current_user.username == admin_user:
        form = BooksPostForm()
        if request.method == 'POST':
            books = Books(
                title = form.title.data,
                author = form.author.data,
                published_by = form.published_by.data,
                published_at = form.published_at.data,
                img_link = form.img_link.data,
                pur_link = form.ecsite_link.data
            )
            
            db.session.add(books)
            db.session.commit()
            flash('新しく本が登録されました')
            return redirect(url_for('books.show_books'))
        return render_template('books/new.html',form=form)


@books.route('/books/<int:id>/edit', methods=['GET'])
@login_required
def edit_books(id):
    book = Books.query.get(id)
    return render_template('books/edit.html', book=book)
 

@books.route('/books/<int:id>/update', methods=['POST'])
@login_required
def update_books(id):
    books = Books.query.get(id)
    books.title = request.form.get('title')
    books.author = request.form.get('author')
    books.published_by = request.form.get('published_by')
    books.published_at = request.form.get('published_at')
    books.img_link = request.form.get('img_link')
    books.pur_link = request.form.get('pur_link')
    
    db.session.merge(books)
    db.session.commit()
    flash('タイトル : {} の記事を更新しました'.format(books.title))
    return redirect(url_for('books.show_books'))

@books.route('/books/<int:id>/delete', methods=['POST'])
@login_required
def delete_books(id):
    books = Books.query.get(id)
    
    db.session.delete(books)
    db.session.commit()
    flash('タイトル : {} の記事を削除しました'.format(books.title))
    return redirect(url_for('books.show_books'))

@books.route('/books/<int:book_id>', methods=['GET'])
def show_book(book_id):
    page = request.args.get('page',1,type=int)
    book = Books.query.get(book_id)
    hoges = BooksPost.query.filter_by(book_id=book_id).order_by(BooksPost.date.asc()).paginate(page=page,per_page=5)

    print(hoges)
    return render_template('books/show.html', book=book, hoges=hoges,admin_user=admin_user,page=page)

################################################
#### Books details 
#################################


@bookspost.route('/books/<int:book_id>/<int:bookspost_id>', methods=['GET'])
def count_bookspost(book_id,bookspost_id):
    book = Books.query.get(book_id)
    bookspost = BooksPost.query.get(bookspost_id)
    bookspost.count += 1
    db.session.commit()
    return redirect(url_for('books.show_book',book_id=book.id,count=bookspost.count))

@bookspost.route('/books/<int:book_id>/create_post',methods=['GET','POST'])
@login_required
def create_post(book_id):
    if current_user.username == admin_user:
        form = BooksPostForm()
        if request.method == 'POST': 
            if form.validate_on_submit: 
                bookspost = BooksPost(
                    book_id=book_id,
                    user_id=current_user.id,
                    title=form.title.data,
                    text=form.text.data,
                    count=0
                )
                
                db.session.add(bookspost)
                db.session.commit()
                flash('本詳細説明が作成されました。')
                return redirect(url_for('books.show_book',book_id=book_id))
        book = Books.query.get(book_id)
        return render_template('books/create_post.html',form=form, book=book)

@bookspost.route('/books/<int:book_id>/<int:bookspost_id>/update', methods=['GET','POST'])
@login_required

def update_post(book_id,bookspost_id):
     if current_user.username == admin_user:
        form = BooksPostForm()
        bookspost = BooksPost.query.get(bookspost_id)
        book = BooksPost.query.filter_by(book_id=book_id).first()
        if request.method == 'POST':
            bookspost.title = form.title.data
            bookspost.text = form.text.data

            db.session.commit()
            flash('本詳細の更新完了')
            return redirect(url_for('books.show_book',book_id=book_id))

        form.title.data = bookspost.title
        form.text.data = bookspost.text

        return render_template('books/create_post.html', form=form, book=book,book_id=book_id,bookspost_id=bookspost.id)


#delete
@bookspost.route('/books/<int:book_id>/<int:bookspost_id>/delete',methods=['GET', 'POST'])
@login_required
def delete_post(book_id, bookspost_id):
    bookspost = BooksPost.query.get_or_404(bookspost_id)
    book = Books.query.get_or_404(book_id)
    if current_user.username != admin_user:
        abort(403)
        
    db.session.delete(bookspost)
    db.session.commit()
    flash('本詳細を削除しました。')
    return redirect(url_for('books.show_book',book_id=book.id))

tech2metailblog/templates/books/create_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="form-signin">
        <h1 class="h3 mb-3 fw-normal">Title :  <p>{{book.title}}</p></h1>
        <form class="form-group" method="POST">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.text.label(class="form-control-label")}}
                {{form.text(class="form-control form-control-lg ")}}
            </div>
            <br>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>

    </div>
</div>

{% endblock %}

tech2metailblog/templates/books/edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<form action="{{ url_for('books.update_books', id=book.id) }}" class="add-books" method="POST">
    <div class="form-group">
        <label for="InputTitle" class="">タイトル</label>
        <input type="text" class="form-control" id="InputTitle" name="title" value="{{ book.title}}">
    </div>

    <div class="form-group">
        <label for="InputTitle" class="">著者</label>
        <input type="text" class="form-control" id="InputTitle" name="author" value="{{ book.author}}">
    </div>

    <div class="form-group">
        <label for="InputTitle" class="">出版者</label>
        <input type="text" class="form-control" id="InputTitle" name="published_by" value="{{ book.published_by}}">
    </div>
    
    <div class="form-group">
        <label for="InputTitle" class="">出版年</label>
        <input type="text" class="form-control" id="InputTitle" name="published_at" value="{{ book.published_at }}">
    </div>

    <div class="form-group">
        <label for="InputTitle" class="">イメージリンク</label>
        <input type="text" class="form-control" id="InputTitle" name="img_link" value="{{ book.img_link}}">
    </div>

    <div class="form-group">
        <label for="InputTitle" class="">ECサイトリンク</label>
        <input type="text" class="form-control" id="InputTitle" name="pur_link" value="{{ book.pur_link}}">
    </div>

        <button type="submit" class="btn btn-primary">更新</button>
</form>
</div>


{% endblock %}

tech2metailblog/templates/books/index.html
{% extends "base.html" %}
{% block content %}
{% if session.logged_in %}
<div class="btn-group">
  <form action="{{ url_for('books.new_book') }}" method="GET">
      <button type="submit" class="btn btn-primary">新規登録</button>
  </form>
</div>
{% endif %}
<div class="table-responsive">
<table class="table table-bordered">  
  <thead>
      <tr>
          <th colspan="1" class="text-center">No.</th>
          <th colspan="1" class="text-center">タイトル</th>
          <th colspan="1" class="text-center">著者</th>
          <th colspan="1" class="text-center">出版者</th>
          <th colspan="1" class="text-center">出版年</th>
          <th colspan="1" class="text-center">img_link</th>
          <th colspan="1" class="text-center">ecsite_link</th>
          <th colspan="1" class="text-center">text</th>
          <th colspan="1" class="text-center">編集</th>
          <th colspan="1" class="text-center">削除</th>
      </tr>
  </thead>
  <tbody>
    {% for book in books %}
      <tr class="text-center"> 
          <td>{{book.id}}</td>
          <td>{{book.title}}</td>
          <td>{{book.author}}</td>
          <td>{{book.published_by}}</td>
          <td>{{book.published_at}}</td>
          <td>{{book.img_link}}</td>
          <td>{{book.pur_link}}</td>
          <td>{{book.text}}</td>
          <td>
            <div class="btn-group">
              <form action="{{ url_for('books.edit_books',id=book.id) }}" method="GET">
                <button type="submit" class="btn btn-primary">編集</button>
              </form>
            </div>
          </td>
          <td>
            <div class="btn-group">
              <form action="{{ url_for('books.delete_books',id=book.id) }}" method="POST">
                <button type="submit" class="btn btn-danger">削除</button>
              </form>
            </div>
          </td>   
      </tr>
      {% endfor %}
  </tbody>
</table>
</div>

 
    {% if books | length == 0 %}
     <body > 
       本がありません
     </body>
    {% endif %}

{% endblock %}

tech2metailblog/templates/books/new.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="form-signin">
        <h1 class="h3 mb-3 fw-normal">Welcome to add a book page. Please post it!</h1>
        <form class="form-group" method="POST">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.author.label(class="form-control-label")}}
                {{form.author(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.published_by.label(class="form-control-label")}}
                {{form.published_by(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.published_at.label(class="form-control-label")}}
                {{form.published_at(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.img_link.label(class="form-control-label")}}
                {{form.img_link(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.ecsite_link.label(class="form-control-label")}}
                {{form.ecsite_link(class="form-control form-control-lg")}}
            </div>

            <br>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info",method='POST')}}
            </div>
        </form>

    </div>
</div>

{% endblock %}

tech2metailblog/templates/books/shelf.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<div class="row ">
{% for book in books %}
  {% if book.id % 2 == 1 %}
  <div class="col-md-6">
      <div class="card col-md-12">
        <div class="row g-0">
          <div class="col-md-4 text-center">
            <img src="{{book.img_link}}"  style="height: 200px;" alt="..." class="ima-fluid">
          </div>
       
          <div class="container col-md-8 text-start">
            <h6>{{book.title}}</h6>
            <p><a href="{{book.pur_link}}" class="btn btn-secondary">外部商品サイトはこちら</a></p>
            <a href="{{url_for('books.show_book',book_id=book.id)}}" class="btn btn-primary">本紹介はこちら</a>
          </div>
        </div>
        
      </div>
  </div>
  {% else %}
  <div class="col-md-6">
    <div class="card col-md-12">
      <div class="row g-0">
        <div class="col-md-4 text-center">
          <img src="{{book.img_link}}"  style="height: 200px;" alt="..." class="ima-fluid">
        </div>
     
        <div class="container col-md-8 text-start">
          <h6>{{book.title}}</h6>
          <p><a href="{{book.pur_link}}" class="btn btn-secondary">外部商品サイトはこちら</a></p>
            <a href="{{url_for('books.show_book',book_id=book.id)}}" class="btn btn-primary">本紹介はこちら</a>
        </div>
      </div>
      
    </div>
</div>
  {% endif %}
{% endfor %}
</div>
</div>
  
{% endblock %}

tech2metailblog/templates/books/show.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <h1>Book Title: {{ book.title }}</h1>
        <h3>Author: {{ book.author }}</h3>
    </div>
   


作成日時: {{ book.created_at.strftime('%Y-%m-%d') }}
<br><br>
{% if current_user.username == admin_user %}
<div class="btn-group">
    <form action="{{ url_for('books.edit_books', id=book.id ) }}" method="GET">
        <button type="submit" class="btn btn-secondary">編集</button>
    </form>
</div>
<div class="btn-group">
    <form action="{{ url_for('books.delete_books', id=book.id ) }}" method="POST">
        <button type="submit" class="btn btn-danger">削除</button>
    </form>
</div>
    
{% endif %}

</div>



<!--Detail of this book-->
<div class="container" > 
    {% if current_user.username == admin_user %}
          <button class="btn btn-secondary">
            <a class="text-white" href="{{url_for('bookspost.create_post',book_id = book.id)}}">投稿</a>
          </button>
    {% endif %}
    {% if hoges.items %}
    {% for post in hoges.items %}
      <div class="card text-start">
          <div class="card-body">
            <h2>{{post.title}}</h2>
            <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
            <br>
            <div class="button-group">
                <form action="{{ url_for('bookspost.count_bookspost',book_id=book.id,bookspost_id=post.id)}}" method="GET">
                     <button type="submit" class="btn btn-primary">
                         いいね！
                         <span class="badge bg-secondary">{{post.count}}</span>
                         <span class="visually-hidden">unread messages</span>
                     </button>
                 </form>
             </div>
             <br>
            {{post.text}}
          </div>
          
          {% if current_user.username == admin_user %}
        
          <button class="btn btn-secondary">
              <a class="text-white" href="{{url_for('bookspost.update_post',bookspost_id=post.id, book_id = book.id)}}">編集</a>
          </button>

          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del-modal">
              削除
          </button>
          <!--modal to delete post-->
              <div class="modal fade" tabindex="-1" id="del-modal" aria-labelledby="del-modalLabel">
                  <div class="modal-dialog">
                  <div class="modal-content">
                          <div class="modal-header">
                          <h5 class="modal-title" id="del-modalLabel">注意！</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                          <p>記事を削除しますが本当によろしいですか？</p>
                          </div>
                          <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                          
                              <form  action="{{url_for('bookspost.delete_post',bookspost_id=post.id,book_id=book.id)}}" method="POST">
                                  <input type="submit" class="btn btn-danger" value="削除">
                              </form>

                          </div>
                  </div>
                  </div>
              </div>
      {% endif %}
      </div>
        {% endfor %}
      
    
    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
            {% for page_num in hoges.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
              {% if hoges.page == page_num %}
                <li class="page-item disabled">
                    <a href="{{url_for('books.show_book',page=page_num,book_id=book.id)}}" class="page-link">{{ page_num }}</a>
                </li>
              {% else %}
                <li class="page-item">
                    <a href="{{url_for('books.show_book',page=page_num,book_id=book.id)}}" class="page-link">{{ page_num }}</a>
                </li>
              {% endif %}
            {% endfor %}
        </ul>
    </nav>
    </div>
    {% else %}
    <div class="text-center">
    <h3>投稿記事がありません。</h3>
    </div>
    {% endif %}

{% endblock %}