tech2metailblog/blog_posts/forms.py
#blog_posts/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text= TextAreaField('Text',validators=[DataRequired()])
    submit=SubmitField('Post')

tech2metailblog/books/forms.py
#books/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BooksPostForm(FlaskForm): 
    title = StringField('Title',validators=[DataRequired()])
    author = StringField('Author',validators=[DataRequired()])
    published_by = StringField('Publisher',validators=[DataRequired()])
    published_at = StringField('Published_at',validators=[DataRequired()])
    img_link = StringField('img_link',validators=[DataRequired()])
    ecsite_link = StringField('ECsite_link',validators=[DataRequired()])
    text= TextAreaField('Text',validators=[DataRequired()])
    submit=SubmitField('Post')

tech2metailblog/contacts/forms.py
#contact/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired,Email


class ContactUserForm(FlaskForm):
    username = StringField('UserName',validators=[DataRequired()])
    email = StringField('Email',validators=[DataRequired(),Email()])
    title = StringField('Title',validators=[DataRequired()])
    text= TextAreaField('お問合せ内容',validators=[DataRequired()])
    submit = SubmitField('Send')

tech2metailblog/blog_posts/views.py
#blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from tech2metailblog import db
from tech2metailblog.models import BlogPost
from tech2metailblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

#blog post
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if request.method == 'POST': 
        if form.validate_on_submit:
            blog_post= BlogPost(
                user_id=current_user.id,
                title=form.title.data,
                text=form.text.data,
            
            )
            
            db.session.add(blog_post)
            db.session.commit()
            flash('ブログが作成されました。')
            return redirect(url_for('core.index'))
    
    return render_template('create_post.html',form=form)

@blog_posts.route('/<int:blog_post_id>')        
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                           date=blog_post.date,post=blog_post)

#update
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    form = BlogPostForm()
    if request.method == "POST":
        if blog_post.author != current_user:
            abort(403)
        
        if form.validate_on_submit:
            blog_post.title = form.title.data
            blog_post.text = form.text.data
            db.session.commit()
            flash('ブログが更新されました。')
            return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
        
        
    form.title.data = blog_post.title
    form.text.data = blog_post.text
        
    return render_template('create_post.html',title='Updating',form=form)
    
    
#delete
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
        
    db.session.delete(blog_post)
    db.session.commit()
    flash('ブログを削除しました。')
    return redirect(url_for('core.index'))
    
    

tech2metailblog/books/views.py
import os, json
from flask import request, redirect, url_for, render_template, flash, session, abort
from flask_login import  login_required, current_user
from tech2metailblog import db
from tech2metailblog.models import Books, BooksPost
from tech2metailblog.books.forms import BooksPostForm
from flask import Blueprint
from tech2metailblog.books.spread_sheet import create_df
import pandas as pd


books = Blueprint('books', __name__)
bookspost = Blueprint('bookspost', __name__)

'''
basedir = os.getcwd()
print(basedir)
l = basedir.split('/')
del l[-1]
l_new = l[0]
for i in range(len(l)):
    l_new = os.path.join(l_new,l[i])
basedir = os.path.join("/",l_new)
dir = os.path.join(basedir,'secrets')
json_file = os.path.join(dir,"admin.json")
open_json = open(json_file,'r')
'''
admin_user = os.getenv('ADMIN_USER_NAME')
# admin_user = 'administrator'
@books.route('/bookshelf')
def create_bookshelf():
    df=create_df()
    rows = df.shape[0]
    for i in range(1,rows+1):
        dict = df[:i:].to_dict()
        try:
            books= Books(
                title = dict['title'][i],
                author = dict['author_family'][i] + " " + dict['author_first'][i],
                published_by = dict['published_by'][i],
                published_at = dict['published_at'][i],
                img_link = dict['img_link'][i],
                pur_link = dict['pur_link'][i]
            )
            db.session.add(books)
            db.session.commit()
            flash('データ作成完了')
        except:
            continue
    return redirect(url_for('books.show_books'))

@books.route('/books/shelf')
def show_shelf():
    books = Books.query.all()
    return render_template('books/shelf.html', books=books)
   
@books.route('/books')
@login_required
def show_books():
    if current_user.username == admin_user:
        books = Books.query.all()
        return render_template('books/index.html', books=books)
    else:
        return render_template('error_pages/403.html')
        
    


@books.route('/books/new', methods=['GET','POST'])
@login_required

def add_books():
    if current_user.username == admin_user:
        form = BooksPostForm()
        if request.method == 'POST':
            books = Books(
                title = form.title.data,
                author = form.author.data,
                published_by = form.published_by.data,
                published_at = form.published_at.data,
                img_link = form.img_link.data,
                pur_link = form.ecsite_link.data
            )
            
            db.session.add(books)
            db.session.commit()
            flash('新しく本が登録されました')
            return redirect(url_for('books.show_books'))
        return render_template('books/new.html',form=form)


@books.route('/books/<int:id>/edit', methods=['GET'])
@login_required
def edit_books(id):
    book = Books.query.get(id)
    return render_template('books/edit.html', book=book)
 

@books.route('/books/<int:id>/update', methods=['POST'])
@login_required
def update_books(id):
    books = Books.query.get(id)
    books.title = request.form.get('title')
    books.author = request.form.get('author')
    books.published_by = request.form.get('published_by')
    books.published_at = request.form.get('published_at')
    books.img_link = request.form.get('img_link')
    books.pur_link = request.form.get('pur_link')
    
    db.session.merge(books)
    db.session.commit()
    flash('タイトル : {} の記事を更新しました'.format(books.title))
    return redirect(url_for('books.show_books'))

@books.route('/books/<int:id>/delete', methods=['POST'])
@login_required
def delete_books(id):
    books = Books.query.get(id)
    
    db.session.delete(books)
    db.session.commit()
    flash('タイトル : {} の記事を削除しました'.format(books.title))
    return redirect(url_for('books.show_books'))

@books.route('/books/<int:book_id>', methods=['GET'])
def show_book(book_id):
    page = request.args.get('page',1,type=int)
    book = Books.query.get(book_id)
    hoges = BooksPost.query.filter_by(book_id=book_id).order_by(BooksPost.date.asc()).paginate(page=page,per_page=5)

    print(hoges)
    return render_template('books/show.html', book=book, hoges=hoges,admin_user=admin_user,page=page)

################################################
#### Books details 
#################################


@bookspost.route('/books/<int:book_id>/<int:bookspost_id>', methods=['GET'])
def count_bookspost(book_id,bookspost_id):
    book = Books.query.get(book_id)
    bookspost = BooksPost.query.get(bookspost_id)
    bookspost.count += 1
    db.session.commit()
    return redirect(url_for('books.show_book',book_id=book.id,count=bookspost.count))

@bookspost.route('/books/<int:book_id>/create_post',methods=['GET','POST'])
@login_required
def create_post(book_id):
    if current_user.username == admin_user:
        form = BooksPostForm()
        if request.method == 'POST': 
            if form.validate_on_submit: 
                bookspost = BooksPost(
                    book_id=book_id,
                    user_id=current_user.id,
                    title=form.title.data,
                    text=form.text.data,
                    count=0
                )
                
                db.session.add(bookspost)
                db.session.commit()
                flash('本詳細説明が作成されました。')
                return redirect(url_for('books.show_book',book_id=book_id))
        book = Books.query.get(book_id)
        return render_template('books/create_post.html',form=form, book=book)

@bookspost.route('/books/<int:book_id>/<int:bookspost_id>/update', methods=['GET','POST'])
@login_required

def update_post(book_id,bookspost_id):
     if current_user.username == admin_user:
        form = BooksPostForm()
        bookspost = BooksPost.query.get(bookspost_id)
        book = BooksPost.query.filter_by(book_id=book_id).first()
        if request.method == 'POST':
            bookspost.title = form.title.data
            bookspost.text = form.text.data

            db.session.commit()
            flash('本詳細の更新完了')
            return redirect(url_for('books.show_book',book_id=book_id))

        form.title.data = bookspost.title
        form.text.data = bookspost.text

        return render_template('books/create_post.html', form=form, book=book,book_id=book_id,bookspost_id=bookspost.id)


#delete
@bookspost.route('/books/<int:book_id>/<int:bookspost_id>/delete',methods=['GET', 'POST'])
@login_required
def delete_post(book_id, bookspost_id):
    bookspost = BooksPost.query.get_or_404(bookspost_id)
    book = Books.query.get_or_404(book_id)
    if current_user.username != admin_user:
        abort(403)
        
    db.session.delete(bookspost)
    db.session.commit()
    flash('本詳細を削除しました。')
    return redirect(url_for('books.show_book',book_id=book.id))

tech2metailblog/contacts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from tech2metailblog import db
from tech2metailblog.models import Contact
from tech2metailblog.contacts.forms import ContactUserForm

contacts= Blueprint('contacts',__name__)

@contacts.route("/contact",methods=['GET','POST'])
@login_required
def contact():
    form = ContactUserForm()
    if request.method == 'POST':
        if form.validate_on_submit:
            if form.email.data == current_user.email:
                print('正常')   
                contact=Contact(
                    username = form.username.data,
                    email = form.email.data,
                    title = form.title.data,
                    text = form.text.data
                    )
                
                db.session.add(contact)
                db.session.commit()
                flash('お問合せメールを送信しました。')
                return redirect(url_for('core.index'))
            else:
                flash('ご登録済のemailアドレスを使用して下さい。')
    
    
    return render_template('contact.html',form=form)

tech2metailblog/core/views.py
# core/views.py

from flask import render_template, request, Blueprint
from tech2metailblog import db
from sqlalchemy import desc
from tech2metailblog.models import Books, BooksPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    booksposts = BooksPost.query.order_by(BooksPost.date.desc()).first()
    book = None
    if booksposts:
        book = Books.query.get_or_404(booksposts.book_id)
    return render_template('index.html',booksposts=booksposts,book=book)

@core.route('/info')
def info():
    return render_template('info.html')

@core.route('/blog')
def blog():
    return render_template('blog.html')

tech2metailblog/users/views.py
#users/views.py

from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from tech2metailblog import db
from tech2metailblog.models import User, BlogPost
from tech2metailblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from tech2metailblog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

#register
@users.route("/signup",methods=["GET", "POST"])
def signup():
    form = RegistrationForm()
    
    if form.validate_on_submit():
        user =User(email=form.email.data,
                   username=form.username.data,
                   password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("ご登録ありがとうございました。")
        return redirect(url_for('users.login'))
    
    return render_template('signup.html',form=form)
    
#Login
@users.route("/login",methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                flash('ログインしました。')
                
                next = request.args.get('next')
                
                if next == None or not next[0]=='/':
                    next = url_for('core.index')
                
                return redirect(next)
            else:
                flash('emailアドレスまたはパスワードが間違っています。')
                return redirect(url_for('users.login'))
            
        else:
            flash('ユーザー名が見つかりません。サインアップを行なってください。')
            return redirect(url_for('users.signup'))
        
    return render_template('login.html',form=form)

#Logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


#account(update Userform)
@users.route('/account/<username>', methods=['GET','POST'])
@login_required
#
def account(username):
    flash(f'ユーザー: {current_user.username} でログイン中')
    form = UpdateUserForm()
    if form.validate_on_submit():
        username = current_user.username
        if form.picture.data:
            flash(f'new_file: {form.picture.data}')
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        if form.username.data != username:
            current_user.username = form.username.data
        if form.email.data != current_user.email:
            current_user.email = form.email.data
        db.session.commit()
        flash('ユーザーアカウントを更新しました。')
        return redirect(url_for('users.account',username=username))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        
    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#user's list if Blog posts
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

tech2metailblog/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.83.1">
        <title>Tech2Metail</title>
        
        <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/carousel/">
    
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
        <!-- Favicons -->
    
    
        <style>
          .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }
    
          @media (min-width: 768px) {
            .bd-placeholder-img-lg {
              font-size: 3.5rem;
            }
          }
        </style>
    
        
        <!-- Custom styles for this template -->
        <link href="{{url_for('static',filename="style.css")}}" rel="stylesheet">
      
   </head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Tech2Metail</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('core.info')}}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('contacts.contact')}}">Contact</a>
                </li>
                
                
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('users.logout')}}" >Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.account',username=current_user.username)}}" >Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('books.show_shelf')}}">Books</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}" >Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.signup')}}" >Sign Up</a>
                </li>
                {% endif %}
              </ul>
              <script async src="https://cse.google.com/cse.js?cx=d6c98cb1149bc0fbd"></script>
              <div class="gcse-search">
                
              </div>
            
            </div>
          </div>
        </nav>
    </header>
    
    <main class="main">
      {% for messages in get_flashed_messages() %}
      <div class="alert alert-info" role="alert">
         {{messages}}
      </div>
      {% endfor %}
      
      {% block content%}
      {% endblock %}
   
        
           
      <!-- FOOTER -->
      <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>&copy; 2022 Tech2Metail. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
        
        
          
        
              
    </main>
</body>
</html>

tech2metailblog/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
          <h1 class="display-4">{{title}}</h1>
          <h2>Written by: {{post.author.username}} </h2>
          <h3>Published on: {{post.date.strftime('%B %d, %Y')}} </h3>
    </div>
    <div>
        <p class="lead my-3">{{post.text}}</p>

        {% if post.author == current_user %}
           <button class="btn btn-secondary">
               <a class="text-white" href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">編集</a>
           </button>

           <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del-modal">
              削除
           </button>
           <!--modal to delete post-->
            <div class="modal fade" tabindex="-1" id="del-modal" aria-labelledby="del-modalLabel">
                <div class="modal-dialog">
                <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="del-modalLabel">注意！</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        <p>記事を削除しますが本当によろしいですか？</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                        
                            <form  action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
                                <input type="submit" class="btn btn-danger" value="削除">
                            </form>

                        </div>
                </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>


{% endblock %}

tech2metailblog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src={{ url_for("static", filename="beach.jpg") }} alt="" width="100%" height="100%" >
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
        
        <div class="container">
          <div class="carousel-caption text-center">
            <h2>「本質に興味がある」</h2>
            <h3>「知的好奇心を満たすことに喜びを感じる」</h3>
            <p>そんな人々と共有したいことがある</p>
            <p>まずは発信していこう</p>
            {% if current_user.is_authenticated%}
            <p><a class="btn btn-lg btn-primary" href="{{url_for('core.info')}}">View details</a></p>
            {% else %}
            <p><a class="btn btn-lg btn-primary" href="{{url_for('users.signup')}}">Sign up today</a></p>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src={{ url_for("static", filename="parchment-g61a8a4583_640.jpg") }} alt="" width="100%" height="100%" class="">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="false" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
            <a href="https://pixabay.com/ja/users/geralt-9301/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4746819">Gerd Altmann</a>による<a href="https://pixabay.com/ja/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4746819">Pixabay</a>からの画像
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src={{ url_for("static", filename="planet-g6ccbb144e_640.jpg") }} alt="" width="100%" height="100%" class="">
        
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
            <a href="https://pixabay.com/ja/users/loganart-665411/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=581239">LoganArt</a>による<a href="https://pixabay.com/ja/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=581239">Pixabay</a>からの画像
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
  
    <div class="container marketing">
  
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="circle" src="{{url_for('static',filename='books-gb9295fff0_640.jpg')}}">
            
          <h2>Books</h2>
          <p>最近読んだ本の紹介をしています。</p>
          <p>認知科学、問題解決、一部歴史など</p>
          <p><a class="btn btn-secondary" href="{{url_for('books.show_shelf')}}">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="circle" src="{{url_for('static',filename='laptop-g97bc331d3_640.jpg')}}">
  
          <h2>Software</h2>
          <p>お気に入りのソフトウェアについて紹介しています。</p>
          <p>#Unreal Engine #Blender #Craft #Dynalist #Unity #Procreate</p>
          <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="circle" src="{{url_for('static',filename='gaming-gb413d174f_640.jpg')}}">
  
          <h2>Games</h2>
          <p>ゲームやスマホアプリの作成について</p>
          <p>Unreal Engine, Blenderを使用したゲーム制作</p>
          <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
  
  
      <!-- START THE FEATURETTES -->
      {% if booksposts%}
      
      <hr class="featurette-divider">
  
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Brand new post</h2>
          <span class="text-muted">It’ll blow your mind.</span>
            <div class="post">
                <h3>この本についての紹介です。</h3>
                <h3>{{book.title}}</h3>
                <img src="{{book.img_link}}" width="100px">
                <div class="" style="padding:2em">
                  <h5>{{ booksposts.title }}</h5>
                  <p >{{ booksposts.text }}</p>
                  <p><a class="btn btn-lg btn-primary" href="{{url_for('books.show_book',book_id=book.id)}}">View details</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        
         
  
        </div>
      </div>
     
      {% else %}
      <hr class="featurette-divider">
  
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Brand new post</h2>
          <span class="text-muted">It’ll blow your mind.</span>
          <p class="lead">投稿記事はありません</p>
        </div>
        <div class="col-md-5">
          <img src="{{book.img_link}}">
         
  
        </div>
      </div>
      {% endif %}
  
      
  
      <!-- /END THE FEATURETTES -->
  
    </div><!-- /.container -->
  
  
{% endblock %}